### ISSUE TITLE
layout.file is a bad name for log file

### ISSUE THREAD

**Issue by mgenov** [Zornica/buildtools#3]
```
mgenov:target(master!?) $ ls
MyJarJar.jar  MyProject.jar layout.file   lib
mgenov:target(master!?) $ 
```

The name of the log file is layout.file which is a bad name for log files. 

applog.log, myproject.log or something like that.

**Comment by mgenov** [comment]
btw, why you are not in the office?

**Comment by Zornica** [comment]
В момента съм в ректората на университета трябва да подам едни документи за
кандидатстване за курс и проект . Щях да ви кажа сутринта.

2015-09-24 14:25 GMT+03:00 Miroslav Genov notifications@github.com:
